### ISSUE TITLE
BitmapConvertor does not exist

### ISSUE THREAD

**Issue by MHaris404** [lavahasif/camera#1]
`using OpenCvSharp.CPlusPlus; using OpenCvSharp.Extensions;`

both does not exist, also I don't have camera.zip file in my project, what is that?

#helpwanted #question #opencvsharp #winform

**Comment by lavahasif** [comment]
Install this Packages Install-Package OpenCvSharp3-WithoutDll -Version 4.0.0.20181129


Install-Package OpenCvSharp-AnyCPU -Version 2.4.10.20170306


near to 100 mb for this open cv dll

here  i used dotnet 4.5  .camera.zip nothing . it same project zipped

**Comment by MHaris404** [comment]
Thank you so much for your reply.
I have used **Aforge.NET**  [Aforge.net](http://www.aforgenet.com/) for the time being and it is working.

Your help is appreciated. Thanks alot.
